### ISSUE TITLE
Update OffSets

### ISSUE THREAD

**Issue by MarioGK** [aevitas/orion#5]
Can you please update the offsets ? thanks, and i love your project learned a lot from it :D

**Comment by aevitas** [comment]
Offsets won't always be up to date - you can always grab the latest from UC or similar. I'll update the offsets when looking into the entity list issue. #6

**Comment by MarioGK** [comment]
Well you could comment on the offsets, i didnt update them by myself because i dont know what they mean, fox example the EnginePtr i searched a lot and didnt found anything about it, thanks for your project i`ll try to learn more from it :D

**Comment by aevitas** [comment]
> fox example the EnginePtr i searched a lot and didnt found anything about it, thanks for your project i`ll try to learn more from it :D

Ah, right. EnginePtr is what's commonly called GameClient I believe. I'll add those comments. Thanks for the suggestion :)

**Comment by aevitas** [comment]
Updated for the december patch of CSGO.
