### ISSUE TITLE
ReadProcessMemory failed! Could not read 4 bytes from 64!

### ISSUE THREAD

**Issue by JoakimCarlsson** [aevitas/orion#6]
Noticed and issue. 

An unhandled exception of type 'BlueRain.Common.BlueRainReadException' occurred in BlueRain.dll
Additional information: ReadProcessMemory failed! Could not read 4 bytes from 64!

All the offsets are up to date, it works great until you aim at the enemy team, that's when the problem first occurs or at random points.

**Comment by aevitas** [comment]
Looks like a possible issue with the entity list - I'll look into it.

**Comment by JoakimCarlsson** [comment]
Assuming getting that dynamically should possible solve this issue?

**Comment by JoakimCarlsson** [comment]
Nevermind that, I see now that it will add all the entities to the player list even though it's not a player, and than it will try to read from that.

**Comment by aevitas** [comment]
@JoakimCarlsson Correct - I should possibly refactor it to take the amount of players in game into account. Right now, it iterates over every entity in the list and adds them to a "Player" list, which is very counter-intuitive.

**Comment by JoakimCarlsson** [comment]
Indeed, after cleaning thay bit up a bit making it sort every entity into it's own Tuple, players goes into a player list and weapons goes into weapons etc and it's working like a charm. Keep up the good work.

**Comment by aevitas** [comment]
@JoakimCarlsson Feel free to submit a pull request that addresses that if you feel it should be in the codebase and you've found an elegant solution to it. :)

**Comment by aevitas** [comment]
Just submitted a PR that ensures only objects whose base address is valid will be exposed via `ObjectManager.Players`. While the underlying collection will still contain invalid objects, those shouldn't be accessible to users of the API anymore, thus ensuring this specific invalid read will not occur again.

**Comment by JoakimCarlsson** [comment]
I'll do that later, what I just do is I check the ClassID, if it's matches CladdId 35 which is a player I put it into the _players list, same goes for weapons I compare them to classId's and if it's matches those they are weapons, and last if there are still entities left I just put them in a _enitites list.
